<?if(!defined("B_PROLOG_INCLUDED")||B_PROLOG_INCLUDED!==true) die();

use \Bitrix\Main\Loader;
use General\User;

if (!Loader::includeModule('iblock'))
    throw new Bitrix\Main\SystemException('Module iblock is not initialized');

if (!Loader::includeModule('currency'))
    throw new Bitrix\Main\SystemException('Module iblock is not initialized');

/** Слайдер */
$rsMarketingBlockSlider = Bitrix\Iblock\Elements\ElementMarketingBlockSliderTable::getList([
    "select" => [
		"ID",
		"IBLOCK_ID",
        "NAME",
		"IBLOCK_SECTION_ID",
        "PREVIEW_TEXT",
        "PREVIEW_PICTURE",
        "MB_PRODUCTS_IN_SLIDER_" => "MB_PRODUCTS_IN_SLIDER.ELEMENT",
		"PRODUCT_PRICE" => "PRICE.PRICE",
		"SECTION_PICTURE" => "SECTION.PICTURE",
    ],
	"runtime" => [
        new \Bitrix\Main\Entity\ReferenceField(
            'PRICE',
            '\Bitrix\Catalog\PriceTable',
            ['=this.MB_PRODUCTS_IN_SLIDER.ELEMENT.ID' => 'ref.PRODUCT_ID']
		),
		new \Bitrix\Main\Entity\ReferenceField(
            'SECTION',
            '\Bitrix\Iblock\SectionTable',
            [
				'=this.IBLOCK_SECTION_ID' => 'ref.ID',
			]
        ),
	],
    "cache" => [
        "ttl" => 12800000
    ]
])->fetchAll();



if (!empty($rsMarketingBlockSlider)) {

	$tmpMarketingBlock = reset($rsMarketingBlockSlider);
	$entity = \Bitrix\Iblock\Model\Section::compileEntityByIblock($tmpMarketingBlock['IBLOCK_ID']);

	$iblockSectionCatalog = $entity::getList(array(
		"select" => ["UF_SECTION_CATALOG"], 
		"filter" => ['ID' => $tmpMarketingBlock['IBLOCK_SECTION_ID']],
		"cache"  => ['ttl' => 12800000],
	))->fetch();

	$previousID = 0;

    foreach ($rsMarketingBlockSlider as $arSliderIndex => $arSlider) {

		if ($arSlider['ID'] == $previousID)
			continue;

		$tmpSectionUrl = CIBlockSection::GetNavChain($arSlider['MB_PRODUCTS_IN_SLIDER_IBLOCK_ID'], $iblockSectionCatalog['UF_SECTION_CATALOG'], false);

		if (!empty($tmpSectionUrl)) {
			while ($res = $tmpSectionUrl->GetNext()) {
				$arResult['DATA_SLIDER'][$arSliderIndex]['SECTION_PAGE_URL'] = $res['SECTION_PAGE_URL'];
			}
		}

        $arResult['DATA_SLIDER'][$arSliderIndex]["NAME"] = $arSlider['NAME'];

		$tmpNameArray = explode(' ', $arSlider['NAME']);

		$arResult['DATA_SLIDER'][$arSliderIndex]['NAME_BOLD'] = array_pop($tmpNameArray);
		$arResult['DATA_SLIDER'][$arSliderIndex]['NAME'] = implode(' ', $tmpNameArray);

		$tmpPrice = (int) $arSlider['PRODUCT_PRICE'];

        $arResult['DATA_SLIDER'][$arSliderIndex]["SECTION_PICTURE"] = CFile::GetPath($arSlider['SECTION_PICTURE']);
		$arResult['DATA_SLIDER'][$arSliderIndex]["PREVIEW_PICTURE"] = CFile::GetPath($arSlider['MB_PRODUCTS_IN_SLIDER_PREVIEW_PICTURE']);

		$arResult['DATA_SLIDER'][$arSliderIndex]["PREVIEW_TEXT"] = $arSlider['PREVIEW_TEXT'];
		
        $arResult['DATA_SLIDER'][$arSliderIndex]["URL"] = 
		'/catalog/' . $arSlider['MB_PRODUCTS_IN_SLIDER_ID'] . '/' . $arSlider['MB_PRODUCTS_IN_SLIDER_CODE'] . '/';

		$arResult['DATA_SLIDER'][$arSliderIndex]["PRODUCT_PRICE"] = str_replace('.',' ', CCurrencyLang::CurrencyFormat($tmpPrice, 'RUB'));

		$previousID = $arSlider['ID'];


    }

}

/** Товары */

$rsMarketingBlockProducts = Bitrix\Iblock\Elements\ElementMarketingBlockTable::getList([
    "select" => [
        "MB_PRODUCTS_" => "MB_PRODUCTS.ELEMENT.ID",
    ],
    "cache" => [
        "ttl" => 12800000
    ]
])->fetchAll();

if (!empty($rsMarketingBlockProducts)) {
    foreach ($rsMarketingBlockProducts as $arProduct) {
        $arResult['MB_PRODUCTS_ID'][$arProduct['MB_PRODUCTS_']] = $arProduct['MB_PRODUCTS_'];
    }
}

/** Акции */
$rsMarketingBlockPromo = Bitrix\Iblock\Elements\ElementMarketingBlockTable::getList([
    "select" => [
        "MB_PROMO_" => "MB_PROMO.ELEMENT",
        "DOP_IMAGE" => "MB_PROMO.ELEMENT.DOP_IMAGE.VALUE"
    ],
    "cache" => [
        "ttl" => 12800000
    ]
])->fetchAll();


if (!empty($rsMarketingBlockPromo)) {

    foreach ($rsMarketingBlockPromo as $arPromo) {

        if (!empty($arPromo['DOP_IMAGE'])) {
            $tmpPicture = CFile::GetPath($arPromo['DOP_IMAGE']);
        } elseif (!empty($arPromo['MB_PROMO_PREVIEW_PICTURE'])) {
            $tmpPicture = CFile::GetPath($arPromo['MB_PROMO_PREVIEW_PICTURE']);
        } elseif (!empty($arPromo['MB_PROMO_DETAIL_PICTURE'])) {
            $tmpPicture = CFile::GetPath($arPromo['MB_PROMO_DETAIL_PICTURE']);
        }

        $arResult['DATA_SECTION_PROMO']['MB_PROMO']['PICTURE'] = $tmpPicture;
        $arResult['DATA_SECTION_PROMO']['MB_PROMO']['URL'] = '/promo/' . $arPromo['MB_PROMO_CODE'] . '/';

    }

    unset($tmpPicture);
}

/** Раздел каталога */
$rsMarketingBlockSectionCatalog = Bitrix\Iblock\Elements\ElementMarketingBlockTable::getList([
    "select" => [
        "MB_SECTION_CATALOG_" => "MB_SECTION_CATALOG.SECTION",
    ],
    "cache" => [
        "ttl" => 12800000
    ]
])->fetchAll();

if (!empty($rsMarketingBlockSectionCatalog)) {

    foreach ($rsMarketingBlockSectionCatalog as $arSection) {
        if (!empty($arSection['MB_SECTION_CATALOG_PICTURE'])) {
            $tmpPicture = CFile::GetPath($arSection['MB_SECTION_CATALOG_PICTURE']);
        } elseif (!empty($arSection['MB_SECTION_CATALOG_DETAIL_PICTURE'])) {
            $tmpPicture = CFile::GetPath($arSection['MB_SECTION_CATALOG_DETAIL_PICTURE']);
        }

		$tmpSectionUrlSect = CIBlockSection::GetNavChain($arSection['MB_SECTION_CATALOG_IBLOCK_ID'], $arSection['MB_SECTION_CATALOG_ID'], false);

		if (!empty($tmpSectionUrlSect)) {
			while ($res = $tmpSectionUrlSect->GetNext()) {
				$arResult['DATA_SECTION_PROMO']['MB_SECTION_CATALOG']['URL'] = $res['SECTION_PAGE_URL'];
			}
		}
		
        $arResult['DATA_SECTION_PROMO']['MB_SECTION_CATALOG']['PICTURE'] = $tmpPicture;


    }

    unset($tmpPicture);
}


/** Заголовки и описания */
$rsMarketingBlockTitlesDesc = Bitrix\Iblock\Elements\ElementMarketingBlockTable::getList([
    "select" => [
        "MB_TITLE_FOR_PROMO_" => "MB_TITLE_FOR_PROMO.VALUE",
        "MB_DESC_FOR_PROMO_" => "MB_DESC_FOR_PROMO.VALUE",
        "MB_TITLE_FOR_SECTION_CATALOG_" => "MB_TITLE_FOR_SECTION_CATALOG.VALUE",
        "MB_DESC_FOR_SECTION_CATALOG_" => "MB_DESC_FOR_SECTION_CATALOG.VALUE"
    ],
    "cache" => [
        "ttl" => 12800000
    ]
])->fetchAll();

if (!empty($rsMarketingBlockTitlesDesc)) {
    foreach ($rsMarketingBlockTitlesDesc as $arTitleDesc) {
        if (!empty($arTitleDesc)) {
            foreach ($arTitleDesc as $arKeyTitleDesc => $arInnerTitleDesc) {
                $tmpTitleDesc = rtrim($arKeyTitleDesc, '_');

                if (
                    $tmpTitleDesc == 'MB_TITLE_FOR_PROMO'
                    ||
                    $tmpTitleDesc == 'MB_DESC_FOR_PROMO'
                ) {
                    $arResult['DATA_SECTION_PROMO']['MB_PROMO'][$tmpTitleDesc] = $arInnerTitleDesc;
                }

                if (
                    $tmpTitleDesc == 'MB_TITLE_FOR_SECTION_CATALOG'
                    ||
                    $tmpTitleDesc == 'MB_DESC_FOR_SECTION_CATALOG'
                ) {
                    $arResult['DATA_SECTION_PROMO']['MB_SECTION_CATALOG'][$tmpTitleDesc] = $arInnerTitleDesc;
                }

                continue;

            }
        }

    }

    unset($tmpTitleDesc);

}

$user = new User();
$priceCode = $user->getUserPriceCode();

$APPLICATION->IncludeComponent(
	"bitrix:catalog.section",
	"products.promo.main",
	Array(
		"ACTION_VARIABLE" => "action",
		"ADD_PICT_PROP" => "-",
		"ADD_PROPERTIES_TO_BASKET" => "Y",
		"ADD_SECTIONS_CHAIN" => "N",
		"ADD_TO_BASKET_ACTION" => "ADD",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_ADDITIONAL" => "",
		"AJAX_OPTION_HISTORY" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"BACKGROUND_IMAGE" => "-",
		"BASKET_URL" => "/personal/basket.php",
		"BROWSER_TITLE" => "-",
		"CACHE_FILTER" => "N",
		"CACHE_GROUPS" => "Y",
		"CACHE_TIME" => "36000000",
		"CACHE_TYPE" => "N",
		"COMPATIBLE_MODE" => "Y",
		"CONVERT_CURRENCY" => "N",
		"CUSTOM_FILTER" => "{\"CLASS_ID\":\"CondGroup\",\"DATA\":{\"All\":\"AND\",\"True\":\"True\"},\"CHILDREN\":[]}",
		"DETAIL_URL" => "",
		"DISABLE_INIT_JS_IN_COMPONENT" => "N",
		"DISPLAY_BOTTOM_PAGER" => "Y",
		"DISPLAY_COMPARE" => "N",
		"DISPLAY_TOP_PAGER" => "N",
		"ELEMENT_SORT_FIELD" => "sort",
		"ELEMENT_SORT_FIELD2" => "id",
		"ELEMENT_SORT_ORDER" => "asc",
		"ELEMENT_SORT_ORDER2" => "desc",
		"ENLARGE_PRODUCT" => "STRICT",
		"FILTER_NAME" => "arrFilterMarketingBlock",
		"HIDE_NOT_AVAILABLE" => "N",
		"HIDE_NOT_AVAILABLE_OFFERS" => "N",
		"IBLOCK_ID" => "16",
		"IBLOCK_TYPE" => "1c_catalog",
		"INCLUDE_SUBSECTIONS" => "Y",
		"LABEL_PROP" => array(),
		"LAZY_LOAD" => "N",
        "ELEMENT_ID" => $arResult['MB_PRODUCTS_ID'],
		"LINE_ELEMENT_COUNT" => "3",
		"LOAD_ON_SCROLL" => "N",
		"MESSAGE_404" => "",
		"MESS_BTN_ADD_TO_BASKET" => "В корзину",
		"MESS_BTN_BUY" => "Купить",
		"MESS_BTN_DETAIL" => "Подробнее",
		"MESS_BTN_LAZY_LOAD" => "Показать ещё",
		"MESS_BTN_SUBSCRIBE" => "Подписаться",
		"MESS_NOT_AVAILABLE" => "Нет в наличии",
		"MESS_NOT_AVAILABLE_SERVICE" => "Недоступно",
		"META_DESCRIPTION" => "-",
		"META_KEYWORDS" => "-",
		"OFFERS_CART_PROPERTIES" => array("DDPRO_IDPODRAZDELENIYAKONTRAGENTA", "DDPRO_DOKUMENTUCHETAPAKETA", "DDPRO_ISPOLZOVATTIPOVUYUPODSISTEMU1S", "DDPRO_RAZRESHITPODPISANIEBEZOTPRAVKI", "ARTIKUL_NA_TOVARE", "BREND", "BREND_1", "KOLICHESTVO", "KONTURPLAGIN_ID", "MODEL_ORUZHIYA", "TIP_3", "TIP_PATRONA", "DDPRO_DDPRO_IDPODRAZDELENIYAKONTRAGENTA", "DDPRO_ISPOLZOVATPODKLYUCHAEMYYMODUL", "DDPRO_ISPOLZOVATSOPOSTAVLENIEPODRAZDELENIY", "DDPRO_PODKLYUCHAEMYYMODULIMYASPRAVOCHNIKA", "ARTIKUL_POSTAVSHCHIKA", "KONTURPLAGIN_VERSIYA", "MAKSIMALNYY_SVETOVOY_POTOK_LYUMEN", "NAIMENOVAENIE_NA_RUSSKOM_YAZYKE", "PRITSELNAYA_SETKA", "TIP_KAPSYULYA", "TIP_KREPLENIYA", "DDPRO_MESTONAKHOZHDENIEPODKLYUCHAEMOGOMODULYA", "DDPRO_OSNOVNOYPAKET", "DIAMETR_OBEKTIVA_RAZMER_LINZY_MM_5", "DIAMETR_MM", "KONTURPLAGIN_PROEKT", "MODEL", "PODSVETKA_PRITSELNOY_SETKI", "PRIMECHANIE", "TSVET_LAZERA", "DDPRO_PODKLYUCHAEMYYMODULSSYLKA", "DDPRO_FORMAT_ID_UPD_SCHF", "VSTROENNNYY_BALLISTICHESKIY_KALKULYATOR", "KONTURPLAGIN_SOSTOYANIE", "MATERIAL_8", "OPISANIE_DLYA_31GR", "TIP_LTSU", "DDPRO_PODKLYUCHAEMYYMODULIMYAOBRABOTKI", "DDPRO_FORMAT_ID_UPD_DOP", "CML2_ARTICLE", "CML2_BASE_UNIT", "KALIBR_2", "PODSVETKA", "CML2_MANUFACTURER", "CML2_TRAITS", "CML2_TAXES", "TEKHNICHESKIE_KHARAKTERISTIKI", "TIP_FONARYA", "CML2_ATTRIBUTES", "CML2_BAR_CODE", "DDPRO_KORREKTIROVOCHNYYPAKET", "DDPRO_PODKLYUCHAEMYYMODULPUT", "DLINA_SM", "NAIMENOVAENIE_NA_ANGLIYSKOM_YAZYKE", "PRINTSIP_DEYSTVIYA", "TIP_OKULYARA", "DDPRO_SOKHRANENNAYAVERSIYAMODULYA", "DDPRO_FORMAT_ID_UKD_KSCHF", "KOMPLEKTATSIYA", "MATERIAL_LOZHA_PRIKLADA", "TIP_KREPLENIYA_SOSHEK", "TSENA_SHCHELCHKA", "DDPRO_REZHIMPROKSI", "DDPRO_FORMAT_ID_UKD_DIS", "VID_PTITSY", "KOLICHESTVO_STVOLOV", "STRANA_PROISKHOZHDENIYA", "TIP_KOLLIMATORNOGO_PRITSELA", "DDPRO_ADRESPROKSISERVERA", "DDPRO_FORMAT_ID_UPD", "VID_PRIZM", "DLINA_STVOLA_STVOLOV", "KRATNOST_", "TOROVAYA_MARKA", "DDPRO_PORTPROKSISERVERA", "DDPRO_FORMAT_ID_UKD", "DIAMETR", "DIAMETR_OBEKTIVA_RAZMER_LINZY_MM", "KALIBR_3", "FIRMA_PROIZVODITEL", "DDPRO_LOGINPROKSISERVERA", "KALIBR_4", "KRATNOST_KH", "PODR_DEPARTMENTID", "TOVARNYY_ZNAK", "TSVET", "DDPRO_OTPECHATOKSERTIFIKATANASERVERE", "DDPRO_PAROLPROKSISERVERA", "DLINA", "KALIBR_5", "STEKLO_PRIZM", "DDPRO_SOKHRANENIEDOKUMENTOVPUT", "DDPRO_SHIFROVATDOKUMENTY", "KRATNOST_KH_1", "MATERIAL", "MATERIAL_LOZHA_PRIKLADA_1", "DDPRO_ZAPISYVATKOMMENTARIIVDOKUMENTY1S", "DDPRO_SOKHRANENIEDOKUMENTOVSTSENARIY", "DIAMETR_1", "DLINA_STVOLA_MM", "MAKSIMALNOE_IZMERYAEMOE_RASSTOYANIE_M", "DDPRO_SOKHRANENIEDOKUMENTOVGRUPPIROVATPOPAKETAM", "DDPRO_TEKSTKOMMENTARIYAPOLUCHENIE", "EMKOST_MAGAZINA", "MINIMALNOE_IZMERYAEMOE_RASSTOYANIE_M", "UROVEN", "DDPRO_AKTCVERKI", "DDPRO_SOKHRANENIEDOKUMENTOVIMYAKATALOGAPAKETA", "VID", "DIAMETR_OBEKTIVA_RAZMER_LINZY_MM_1", "PRINTSIP_DEYSTVIYA_1", "DDPRO_SOKHRANENIEDOKUMENTOVIMYAKATALOGAPAKETAPOUMO", "DDPRO_SCHETNAOPLATU", "VES_PULI_G", "KRATNOST_KH_2", "TIP_ZASIDKI", "DDPRO_ZAGRUZHATDOKUMENTOOBOROTTSELIKOM", "DDPRO_SCHETFAKTURANAAVANS", "MATERIAL_4", "PRIMANIVAEMAYA_DICH", "TIP_PULI", "DDPRO_FORMAT_ID_AKTFORMALIZOVANNYY", "DDPRO_KHRANITDOKUMENTYNADISKE", "NA", "TIP_KRONSHTEYNA", "TIP_RASPYLENIYA", "DDPRO_KORNEVOYKATALOGDOKUMENTOV", "DDPRO_FORMAT_ID_TORG12", "TIP_MISHENI_", "TIP_OSNOVANIYA", "TIP_TOVARA_1", "DDPRO_SROKOCHISTKIDOKUMENTOV", "DDPRO_FORMAT_ID_SCHETFAKTURA", "KREPLENIE_1", "NAZNACHENIE_1", "TSVET_1", "DDPRO_UDALYATSODERZHIMOEUSTAREVSHIKHDOKUMENTOV", "DDPRO_FORMAT_ID_ISF", "KREPLENIE", "PRIMANIVAEMOE_ZHIVOTNOE_PTITSA_", "SVET", "DDPRO_ZAPRETITRABOTUSMETRIKAMI", "DDPRO_FORMAT_ID_IUPD", "MATERIAL_5", "TIP_4", "TIPORAZMER", "DDPRO_RAZRESHITDLITELNYEOPERATSIIVFONE", "DDPRO_FORMAT_ID_IUPD_SCHF", "DIAMETR_OBEKTIVA_RAZMER_LINZY_MM_2", "KALIBR", "RASTSVETKA", "DDPRO_IMYATIPOVOGOMODULYAINTEGRATSII", "DDPRO_FORMAT_ID_IUPD_DOP", "KALIBR_1", "KRATNOST_KH_3", "OTSTROYKA_PARALLAKSA", "DDPRO_ZAGRUZHATISKHODYASHCHIEDOKUMENTY", "DDPRO_FORMAT_ID_KSF", "VES_PULKI", "KOMPLEKTY_DLYA_SAYTA", "TIP_TOVARA_NABORY_DLYA_CHISTKI", "DDPRO_ZAGRUZHATVKHODYASHCHIEDOKUMENTY", "DDPRO_FORMAT_ID_IKSF", "DLINA_LEZVIYA", "KOLICHESTVO_V_BANKE", "RAZMER_AKSESSUAROV_", "DDPRO_ZAGRUZHATDOKUMENTYPOSOPOSTAVLENNYMKONTRAGENT", "DDPRO_FORMAT_ID_IUKD", "DLINA_NOZHA", "ISTOCHNIK_ENERGII_", "RAZMER_NOSKI", "DDPRO_SLUZHEBNAYAUCHETNAYAZAPISLOGIN", "DDPRO_FORMAT_ID_IUKD_KSCHF", "MATERIAL_RUKOYATI", "NALICHIE_UPORA_", "RAZMER_OBUV", "DDPRO_SLUZHEBNAYAUCHETNAYAZAPISPAROL", "DDPRO_FORMAT_ID_IUKD_DIS", "DIAMETR_SHARIKA", "MARKA_STALI", "RAZMER_ODEZHDA_ZHENSKAYA", "DDPRO_PUTKMODULYUVSPRAVOCHNIKE1S", "DDPRO_FORMAT_ID_SCHET", "DIAMETR_OBEKTIVA_RAZMER_LINZY_MM_3", "OBYEM_RYUKZAKI_", "TIP", "DDPRO_OTKLYUCHITPREVYUNEFORMALIZOVANNOGO", "DDPRO_FORMAT_ID_SCHETFORMALIZOVANNYY", "DIADOKISPOLZOVATSERVISKONTURMARKIROVKA", "DIAMETR_TRUBY_PRITSELA_MM", "KREPLENIE_", "DDPRO_OTKLYUCHITKONTROLDUBLIROVANIYAOTPRAVKIPAKETO", "DDPRO_FORMAT_ID_AKTSVERKI", "MATERIAL_1", "FOKALNAYA_PLOSKOST", "ELEMENT_PITANIYA", "DDPRO_VIDPAKETA", "DDPRO_SOKHRANENNAYAVERSIYAMODULYAKHRANENIYA", "TIP_KAMUFLYAZHA", "TSVET_5", "TSENA_SHCHELCHKA_1", "DDPRO_REZHIMLOGIROVANIYA", "IDENTIFIKATORDOKUMENTAVDIADOKSCH", "KRATNOST_KH_4", "ROST", "TSVET_2", "DDPRO_IDPODRAZDELENIYAORGANIZATSII", "DDPRO_KATALOGLOGIROVANIYA", "MATERIAL_6", "RAZMER", "TIP_1", "DDPRO_PEREOTPRAVLYAEMYYPAKET", "DDPRO_RAZVORACHIVATPAKETYNAOTPRAVKUPODOKUMENTAM", "DULNAYA_ENERGIYA", "MATERIAL_2", "DDPRO_POKAZYVATKOLICHESTVODOKUMENTOVVSPISKE", "DDPRO_SOZDAVATPEREDATOCHNYEDOKUMENTY", "BLOUBEK", "MODEL_PISTOLETA_", "DDPRO_DDPRO_IDPODRAZDELENIYAORGANIZATSII", "DDPRO_SOZDAVATSCHETAFAKTURY", "PRIMANIVAEMOE_ZHIVOTNOE", "TSVET_3", "DDPRO_UDALYATPRIPEREOTPRAVKEPREDYDUSHCHIYDOKUMENT", "TIP_2", "TIP_KREPLENIYA_1", "DDPRO_OTKLYUCHITANALIZDLYAVKHODYASHCHIKHDOKUMENTOV", "SKLADNOE_IZGOLOVE", "TIP_OPORY", "DDPRO_IDENTIFIKATORBAZY1S", "VYSOTA_STULA", "CHUVSTVITELNOST_SNR", "DDPRO_TOCHNOSTTSENY", "UPRAVLENIE_", "TSVET_LINZ", "DDPRO_TOCHNOSTKOLICHESTVA", "DALNOST_OBNARUZHENIYA_CHELOVEKA_M", "TIP_TOVARA", "DDPRO_ISPOLZOVATSERVISKONTURMARKIROVKA", "KRATNOST_KH_5", "NAZNACHENIE", "DDPRO_AVTOMATICHESKIOBNOVLYATMODUL", "DIAMETR_OBEKTIVA_RAZMER_LINZY_MM_4", "OBEM_ML", "DDPRO_PROPUSTITOBNOVLENIEBIBLIOTEK", "MATERIAL_3", "MATERIAL_7", "DDPRO_IMYAINTEGRATSIONNOGOMODULYA", "TSVET_4", "DDPRO_NASTROYKIKONTURPLAGINY", "KATEGORIYA_TYUNINGA_", "DDPRO_ISPOLZOVATPLAGINY"),
		"OFFERS_FIELD_CODE" => array("ID", "CODE", "XML_ID", "NAME", "TAGS", "SORT", "PREVIEW_TEXT", "PREVIEW_PICTURE", "DETAIL_TEXT", "DETAIL_PICTURE", "DATE_ACTIVE_FROM", "ACTIVE_FROM", "DATE_ACTIVE_TO", "ACTIVE_TO", "SHOW_COUNTER", "SHOW_COUNTER_START", "IBLOCK_TYPE_ID", "IBLOCK_ID", "IBLOCK_CODE", "IBLOCK_NAME", "IBLOCK_EXTERNAL_ID", "DATE_CREATE", "CREATED_BY", "CREATED_USER_NAME", "TIMESTAMP_X", "MODIFIED_BY", "USER_NAME", ""),
		"OFFERS_LIMIT" => "5",
		"OFFERS_PROPERTY_CODE" => array("DDPRO_IDPODRAZDELENIYAKONTRAGENTA", "DDPRO_DOKUMENTUCHETAPAKETA", "DDPRO_ISPOLZOVATTIPOVUYUPODSISTEMU1S", "DDPRO_RAZRESHITPODPISANIEBEZOTPRAVKI", "ARTIKUL_NA_TOVARE", "BREND", "BREND_1", "KOLICHESTVO", "KONTURPLAGIN_ID", "MODEL_ORUZHIYA", "TIP_3", "TIP_PATRONA", "DDPRO_DDPRO_IDPODRAZDELENIYAKONTRAGENTA", "DDPRO_ISPOLZOVATPODKLYUCHAEMYYMODUL", "DDPRO_ISPOLZOVATSOPOSTAVLENIEPODRAZDELENIY", "DDPRO_PODKLYUCHAEMYYMODULIMYASPRAVOCHNIKA", "ARTIKUL_POSTAVSHCHIKA", "KONTURPLAGIN_VERSIYA", "MAKSIMALNYY_SVETOVOY_POTOK_LYUMEN", "NAIMENOVAENIE_NA_RUSSKOM_YAZYKE", "PRITSELNAYA_SETKA", "TIP_KAPSYULYA", "TIP_KREPLENIYA", "DDPRO_MESTONAKHOZHDENIEPODKLYUCHAEMOGOMODULYA", "DDPRO_OSNOVNOYPAKET", "DIAMETR_OBEKTIVA_RAZMER_LINZY_MM_5", "DIAMETR_MM", "KONTURPLAGIN_PROEKT", "MODEL", "PODSVETKA_PRITSELNOY_SETKI", "PRIMECHANIE", "TSVET_LAZERA", "DDPRO_PODKLYUCHAEMYYMODULSSYLKA", "DDPRO_FORMAT_ID_UPD_SCHF", "VSTROENNNYY_BALLISTICHESKIY_KALKULYATOR", "KONTURPLAGIN_SOSTOYANIE", "MATERIAL_8", "OPISANIE_DLYA_31GR", "TIP_LTSU", "DDPRO_PODKLYUCHAEMYYMODULIMYAOBRABOTKI", "DDPRO_FORMAT_ID_UPD_DOP", "CML2_ARTICLE", "CML2_BASE_UNIT", "KALIBR_2", "MORE_PHOTO", "PODSVETKA", "CML2_MANUFACTURER", "CML2_TRAITS", "CML2_TAXES", "TEKHNICHESKIE_KHARAKTERISTIKI", "TIP_FONARYA", "FILES", "CML2_ATTRIBUTES", "CML2_BAR_CODE", "DDPRO_KORREKTIROVOCHNYYPAKET", "DDPRO_PODKLYUCHAEMYYMODULPUT", "DLINA_SM", "NAIMENOVAENIE_NA_ANGLIYSKOM_YAZYKE", "PRINTSIP_DEYSTVIYA", "TIP_OKULYARA", "DDPRO_SOKHRANENNAYAVERSIYAMODULYA", "DDPRO_FORMAT_ID_UKD_KSCHF", "KOMPLEKTATSIYA", "MATERIAL_LOZHA_PRIKLADA", "TIP_KREPLENIYA_SOSHEK", "TSENA_SHCHELCHKA", "DDPRO_REZHIMPROKSI", "DDPRO_FORMAT_ID_UKD_DIS", "VID_PTITSY", "KOLICHESTVO_STVOLOV", "STRANA_PROISKHOZHDENIYA", "TIP_KOLLIMATORNOGO_PRITSELA", "DDPRO_ADRESPROKSISERVERA", "DDPRO_FORMAT_ID_UPD", "VID_PRIZM", "DLINA_STVOLA_STVOLOV", "KRATNOST_", "TOROVAYA_MARKA", "DDPRO_PORTPROKSISERVERA", "DDPRO_FORMAT_ID_UKD", "DIAMETR", "DIAMETR_OBEKTIVA_RAZMER_LINZY_MM", "KALIBR_3", "FIRMA_PROIZVODITEL", "DDPRO_LOGINPROKSISERVERA", "KALIBR_4", "KRATNOST_KH", "PODR_DEPARTMENTID", "TOVARNYY_ZNAK", "TSVET", "DDPRO_OTPECHATOKSERTIFIKATANASERVERE", "DDPRO_PAROLPROKSISERVERA", "DLINA", "KALIBR_5", "STEKLO_PRIZM", "DDPRO_SOKHRANENIEDOKUMENTOVPUT", "DDPRO_SHIFROVATDOKUMENTY", "KRATNOST_KH_1", "MATERIAL", "MATERIAL_LOZHA_PRIKLADA_1", "DDPRO_ZAPISYVATKOMMENTARIIVDOKUMENTY1S", "DDPRO_SOKHRANENIEDOKUMENTOVSTSENARIY", "DIAMETR_1", "DLINA_STVOLA_MM", "MAKSIMALNOE_IZMERYAEMOE_RASSTOYANIE_M", "DDPRO_SOKHRANENIEDOKUMENTOVGRUPPIROVATPOPAKETAM", "DDPRO_TEKSTKOMMENTARIYAPOLUCHENIE", "EMKOST_MAGAZINA", "MINIMALNOE_IZMERYAEMOE_RASSTOYANIE_M", "UROVEN", "DDPRO_AKTCVERKI", "DDPRO_SOKHRANENIEDOKUMENTOVIMYAKATALOGAPAKETA", "VID", "DIAMETR_OBEKTIVA_RAZMER_LINZY_MM_1", "PRINTSIP_DEYSTVIYA_1", "DDPRO_SOKHRANENIEDOKUMENTOVIMYAKATALOGAPAKETAPOUMO", "DDPRO_SCHETNAOPLATU", "VES_PULI_G", "KRATNOST_KH_2", "TIP_ZASIDKI", "DDPRO_ZAGRUZHATDOKUMENTOOBOROTTSELIKOM", "DDPRO_SCHETFAKTURANAAVANS", "MATERIAL_4", "PRIMANIVAEMAYA_DICH", "TIP_PULI", "DDPRO_FORMAT_ID_AKTFORMALIZOVANNYY", "DDPRO_KHRANITDOKUMENTYNADISKE", "NA", "TIP_KRONSHTEYNA", "TIP_RASPYLENIYA", "DDPRO_KORNEVOYKATALOGDOKUMENTOV", "DDPRO_FORMAT_ID_TORG12", "TIP_MISHENI_", "TIP_OSNOVANIYA", "TIP_TOVARA_1", "DDPRO_SROKOCHISTKIDOKUMENTOV", "DDPRO_FORMAT_ID_SCHETFAKTURA", "KREPLENIE_1", "NAZNACHENIE_1", "TSVET_1", "DDPRO_UDALYATSODERZHIMOEUSTAREVSHIKHDOKUMENTOV", "DDPRO_FORMAT_ID_ISF", "KREPLENIE", "PRIMANIVAEMOE_ZHIVOTNOE_PTITSA_", "SVET", "DDPRO_ZAPRETITRABOTUSMETRIKAMI", "DDPRO_FORMAT_ID_IUPD", "MATERIAL_5", "TIP_4", "TIPORAZMER", "DDPRO_RAZRESHITDLITELNYEOPERATSIIVFONE", "DDPRO_FORMAT_ID_IUPD_SCHF", "DIAMETR_OBEKTIVA_RAZMER_LINZY_MM_2", "KALIBR", "RASTSVETKA", "DDPRO_IMYATIPOVOGOMODULYAINTEGRATSII", "DDPRO_FORMAT_ID_IUPD_DOP", "KALIBR_1", "KRATNOST_KH_3", "OTSTROYKA_PARALLAKSA", "DDPRO_ZAGRUZHATISKHODYASHCHIEDOKUMENTY", "DDPRO_FORMAT_ID_KSF", "VES_PULKI", "KOMPLEKTY_DLYA_SAYTA", "TIP_TOVARA_NABORY_DLYA_CHISTKI", "DDPRO_ZAGRUZHATVKHODYASHCHIEDOKUMENTY", "DDPRO_FORMAT_ID_IKSF", "DLINA_LEZVIYA", "KOLICHESTVO_V_BANKE", "RAZMER_AKSESSUAROV_", "DDPRO_ZAGRUZHATDOKUMENTYPOSOPOSTAVLENNYMKONTRAGENT", "DDPRO_FORMAT_ID_IUKD", "DLINA_NOZHA", "ISTOCHNIK_ENERGII_", "RAZMER_NOSKI", "DDPRO_SLUZHEBNAYAUCHETNAYAZAPISLOGIN", "DDPRO_FORMAT_ID_IUKD_KSCHF", "MATERIAL_RUKOYATI", "NALICHIE_UPORA_", "RAZMER_OBUV", "DDPRO_SLUZHEBNAYAUCHETNAYAZAPISPAROL", "DDPRO_FORMAT_ID_IUKD_DIS", "DIAMETR_SHARIKA", "MARKA_STALI", "RAZMER_ODEZHDA_ZHENSKAYA", "DDPRO_PUTKMODULYUVSPRAVOCHNIKE1S", "DDPRO_FORMAT_ID_SCHET", "DIAMETR_OBEKTIVA_RAZMER_LINZY_MM_3", "OBYEM_RYUKZAKI_", "TIP", "DDPRO_OTKLYUCHITPREVYUNEFORMALIZOVANNOGO", "DDPRO_FORMAT_ID_SCHETFORMALIZOVANNYY", "DIADOKISPOLZOVATSERVISKONTURMARKIROVKA", "DIAMETR_TRUBY_PRITSELA_MM", "KREPLENIE_", "DDPRO_OTKLYUCHITKONTROLDUBLIROVANIYAOTPRAVKIPAKETO", "DDPRO_FORMAT_ID_AKTSVERKI", "MATERIAL_1", "FOKALNAYA_PLOSKOST", "ELEMENT_PITANIYA", "DDPRO_VIDPAKETA", "DDPRO_SOKHRANENNAYAVERSIYAMODULYAKHRANENIYA", "TIP_KAMUFLYAZHA", "TSVET_5", "TSENA_SHCHELCHKA_1", "DDPRO_REZHIMLOGIROVANIYA", "IDENTIFIKATORDOKUMENTAVDIADOKSCH", "KRATNOST_KH_4", "ROST", "TSVET_2", "DDPRO_IDPODRAZDELENIYAORGANIZATSII", "DDPRO_KATALOGLOGIROVANIYA", "MATERIAL_6", "RAZMER", "TIP_1", "DDPRO_PEREOTPRAVLYAEMYYPAKET", "DDPRO_RAZVORACHIVATPAKETYNAOTPRAVKUPODOKUMENTAM", "DULNAYA_ENERGIYA", "MATERIAL_2", "DDPRO_POKAZYVATKOLICHESTVODOKUMENTOVVSPISKE", "DDPRO_SOZDAVATPEREDATOCHNYEDOKUMENTY", "BLOUBEK", "MODEL_PISTOLETA_", "DDPRO_DDPRO_IDPODRAZDELENIYAORGANIZATSII", "DDPRO_SOZDAVATSCHETAFAKTURY", "PRIMANIVAEMOE_ZHIVOTNOE", "TSVET_3", "DDPRO_UDALYATPRIPEREOTPRAVKEPREDYDUSHCHIYDOKUMENT", "TIP_2", "TIP_KREPLENIYA_1", "DDPRO_OTKLYUCHITANALIZDLYAVKHODYASHCHIKHDOKUMENTOV", "SKLADNOE_IZGOLOVE", "TIP_OPORY", "DDPRO_IDENTIFIKATORBAZY1S", "VYSOTA_STULA", "CHUVSTVITELNOST_SNR", "DDPRO_TOCHNOSTTSENY", "UPRAVLENIE_", "TSVET_LINZ", "DDPRO_TOCHNOSTKOLICHESTVA", "DALNOST_OBNARUZHENIYA_CHELOVEKA_M", "TIP_TOVARA", "DDPRO_ISPOLZOVATSERVISKONTURMARKIROVKA", "KRATNOST_KH_5", "NAZNACHENIE", "DDPRO_AVTOMATICHESKIOBNOVLYATMODUL", "DIAMETR_OBEKTIVA_RAZMER_LINZY_MM_4", "OBEM_ML", "DDPRO_PROPUSTITOBNOVLENIEBIBLIOTEK", "MATERIAL_3", "MATERIAL_7", "DDPRO_IMYAINTEGRATSIONNOGOMODULYA", "TSVET_4", "DDPRO_NASTROYKIKONTURPLAGINY", "KATEGORIYA_TYUNINGA_", "DDPRO_ISPOLZOVATPLAGINY", ""),
		"OFFERS_SORT_FIELD" => "sort",
		"OFFERS_SORT_FIELD2" => "id",
		"OFFERS_SORT_ORDER" => "asc",
		"OFFERS_SORT_ORDER2" => "desc",
		"PAGER_BASE_LINK_ENABLE" => "N",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
		"PAGER_SHOW_ALL" => "N",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_TEMPLATE" => ".default",
		"PAGER_TITLE" => "Товары",
		"PAGE_ELEMENT_COUNT" => "4",
		"PARTIAL_PRODUCT_PROPERTIES" => "N",
		"PRICE_CODE" => $priceCode,
		"PRICE_VAT_INCLUDE" => "Y",
		"PRODUCT_BLOCKS_ORDER" => "price,props,sku,quantityLimit,quantity,buttons",
		"PRODUCT_DISPLAY_MODE" => "N",
		"PRODUCT_ID_VARIABLE" => "id",
		"PRODUCT_PROPERTIES" => array("DLINA_SM", "KOLICHESTVO", "MATERIAL_LOZHA_PRIKLADA", "TIP_PATRONA", "VID_PTITSY", "KOLICHESTVO_STVOLOV", "PRITSELNAYA_SETKA", "TIP_KAPSYULYA", "TIP_TERMOSA", "DIAMETR_MM", "DLINA_STVOLA_STVOLOV", "OBYEM_L", "PODSVETKA_PRITSELNOY_SETKI", "VALYUTA", "VID_PRIZM", "VSTROENNNYY_BALLISTICHESKIY_KALKULYATOR", "KALIBR_3", "BREND_1", "DIAMETR_OBEKTIVA_RAZMER_LINZY_MM", "KALIBR_4", "PODSVETKA", "TIP_FONARYA", "GRUPPA_KALIBROV_", "KALIBR_5", "KRATNOST_KH", "TIP_OKULYARA", "MATERIAL_LOZHA_PRIKLADA_1", "OSNOVNOE_SVOYSTVO", "STEKLO_PRIZM", "TIP_KREPLENIYA_SOSHEK", "TSENA_SHCHELCHKA", "DIAMETR_KOLETS", "DLINA_STVOLA_MM", "KRATNOST_KH_1", "TIP_KOLLIMATORNOGO_PRITSELA", "VSTROENNYY_LAZERNYY_DALNOMER_", "DIAMETR", "EMKOST_MAGAZINA", "KRATNOST_", "MAKSIMALNOE_IZMERYAEMOE_RASSTOYANIE_M", "MINIMALNOE_IZMERYAEMOE_RASSTOYANIE_M", "PRINTSIP_DEYSTVIYA_1", "TSVET", "VES_PULI_G", "DIAMETR_OBEKTIVA_RAZMER_LINZY_MM_1", "DLINA", "KRATNOST_KH_2", "MATERIAL", "TIP_PULI", "DIAMETR_1", "MARKA_STALI_NOZHI_UD", "MATERIAL_3", "NOMER_DROBI_DIAMETR_KARTECHI", "TIP_TOVARA_1", "MATERIAL_RUKOYATI_NOZHI_UD", "NA", "NAZNACHENIE_1", "UROVEN", "VID", "SVET", "TIP_OSNOVANIYA", "KREPLENIE_1", "TIP_4", "TIP_ZASIDKI", "TIP_NOZHA_NOZHI_UD", "PRIMANIVAEMAYA_DICH", "PRIMANIVAEMOE_ZHIVOTNOE_PTITSA_", "RASTSVETKA", "TIP_STALI_NOZHI_UD", "BREND", "MATERIAL_4", "OBEM_ML_1", "OTSTROYKA_PARALLAKSA", "TIP_MISHENI_", "DIAMETR_OBEKTIVA_RAZMER_LINZY_MM_2", "TIP_KRONSHTEYNA", "TIP_RASPYLENIYA", "TSVET_1", "KRATNOST_KH_3", "KREPLENIE", "TIP_TOVARA_NABORY_DLYA_CHISTKI", "DLINA_LEZVIYA", "KALIBR", "DLINA_NOZHA", "KALIBR_1", "RAZMER_1", "VES_PULKI", "MATERIAL_RUKOYATI", "KOLICHESTVO_V_BANKE", "MARKA_STALI", "DIAMETR_OBEKTIVA_RAZMER_LINZY_MM_3", "ISTOCHNIK_ENERGII_", "ELEMENT_PITANIYA", "DIAMETR_TRUBY_PRITSELA_MM", "NALICHIE_UPORA_", "TSVET_5", "DIAMETR_SHARIKA", "ROST", "FOKALNAYA_PLOSKOST", "TIP", "TSENA_SHCHELCHKA_1", "KRATNOST_KH_4", "KREPLENIE_", "MATERIAL_1", "MATERIAL_5", "OBYEM_RYUKZAKI_", "DULNAYA_ENERGIYA", "TIP_KAMUFLYAZHA", "NACHALNAYA_SKOROST_PULI", "TSVET_2", "BLOUBEK", "OSNOVNOY_MATERIAL", "TIP_1", "PRIMANIVAEMOE_ZHIVOTNOE", "TSVET_3", "TIP_2", "TIP_KREPLENIYA_1", "MATERIAL_8", "SKLADNOE_IZGOLOVE", "TIP_OPORY", "VYSOTA_STULA", "MODEL_PISTOLETA_", "CHUVSTVITELNOST_SNR", "UPRAVLENIE_", "TSVET_LINZ", "DALNOST_OBNARUZHENIYA_CHELOVEKA_M", "TIP_TOVARA", "KRATNOST_KH_5", "NAZNACHENIE", "OBEM_ML", "RAZRESHENIE_MATRITSY", "DIAMETR_OBEKTIVA_RAZMER_LINZY_MM_4", "DLYA_ORUZHIYA_TYUNING", "MATERIAL_2", "EMKOST_TYUNING", "MATERIAL_6", "TSVET_4", "KALIBR_TYUNING", "KATEGORIYA_TYUNINGA_", "TIP_3", "MAKSIMALNYY_SVETOVOY_POTOK_LYUMEN", "MASSA_TYUNING", "MODEL_ORUZHIYA", "DIAMETR_OBEKTIVA_RAZMER_LINZY_MM_5", "OSNOVNOY_MATERIAL_TYUNING", "TIP_KREPLENIYA", "MATERIAL_7", "PATRON", "TSVET_LAZERA", "KALIBR_2", "PLATFORMA_TYUNING", "ISTOCHNIK_SVETA", "TIP_LTSU", "GRAVIROVANNAYA_SETKA", "PRINTSIP_DEYSTVIYA", "REZBA_TYUNING", "TIP_TYUNING", "HIT", "NEW_PRODUCT", "DOUBLE_BONUS", "BUY_WITH_THIS"),
		"PRODUCT_PROPS_VARIABLE" => "prop",
		"PRODUCT_QUANTITY_VARIABLE" => "quantity",
		"PRODUCT_ROW_VARIANTS" => "[{'VARIANT':'2','BIG_DATA':false},{'VARIANT':'2','BIG_DATA':false},{'VARIANT':'2','BIG_DATA':false},{'VARIANT':'2','BIG_DATA':false},{'VARIANT':'2','BIG_DATA':false},{'VARIANT':'2','BIG_DATA':false}]",
		"PRODUCT_SUBSCRIPTION" => "Y",
		"PROPERTY_CODE" => array("DDPRO_IDPODRAZDELENIYAKONTRAGENTA", "DDPRO_DOKUMENTUCHETAPAKETA", "DDPRO_ISPOLZOVATTIPOVUYUPODSISTEMU1S", "DDPRO_RAZRESHITPODPISANIEBEZOTPRAVKI", "WEBSSYLKA_SPRAVOCHNIK_NOMENKLATURA_OBSHCHIE_", "DLINA_SM", "KOLICHESTVO", "KONTURPLAGIN_ID", "MATERIAL_LOZHA_PRIKLADA", "TIP_PATRONA", "DDPRO_DDPRO_IDPODRAZDELENIYAKONTRAGENTA", "DDPRO_ISPOLZOVATPODKLYUCHAEMYYMODUL", "DDPRO_ISPOLZOVATSOPOSTAVLENIEPODRAZDELENIY", "DDPRO_PODKLYUCHAEMYYMODULIMYASPRAVOCHNIKA", "VID_PTITSY", "KOLICHESTVO_STVOLOV", "KONTURPLAGIN_VERSIYA", "PRITSELNAYA_SETKA", "TIP_KAPSYULYA", "TIP_TERMOSA", "DDPRO_MESTONAKHOZHDENIEPODKLYUCHAEMOGOMODULYA", "DDPRO_OSNOVNOYPAKET", "DIAMETR_MM", "DLINA_STVOLA_STVOLOV", "KONTURPLAGIN_PROEKT", "OBYEM_L", "PODSVETKA_PRITSELNOY_SETKI", "PRIMECHANIE", "DDPRO_PODKLYUCHAEMYYMODULSSYLKA", "DDPRO_FORMAT_ID_UPD_SCHF", "VALYUTA", "VID_PRIZM", "VSTROENNNYY_BALLISTICHESKIY_KALKULYATOR", "KALIBR_3", "KONTURPLAGIN_SOSTOYANIE", "CML2_ARTICLE", "BREND_1", "DIAMETR_OBEKTIVA_RAZMER_LINZY_MM", "KALIBR_4", "PODSVETKA", "SIZE_DISCOUNT", "TIP_FONARYA", "GRUPPA_KALIBROV_", "KALIBR_5", "KRATNOST_KH", "TIP_OKULYARA", "MATERIAL_LOZHA_PRIKLADA_1", "OSNOVNOE_SVOYSTVO", "STEKLO_PRIZM", "TIP_KREPLENIYA_SOSHEK", "TSENA_SHCHELCHKA", "DIAMETR_KOLETS", "DLINA_STVOLA_MM", "KRATNOST_KH_1", "TIP_KOLLIMATORNOGO_PRITSELA", "VSTROENNYY_LAZERNYY_DALNOMER_", "DIAMETR", "EMKOST_MAGAZINA", "KRATNOST_", "MAKSIMALNOE_IZMERYAEMOE_RASSTOYANIE_M", "MINIMALNOE_IZMERYAEMOE_RASSTOYANIE_M", "PRINTSIP_DEYSTVIYA_1", "TSVET", "VES_PULI_G", "DIAMETR_OBEKTIVA_RAZMER_LINZY_MM_1", "DLINA", "DLINA_KLINKA_NOZHI_UD", "KRATNOST_KH_2", "MATERIAL", "TIP_PULI", "DIAMETR_1", "MARKA_STALI_NOZHI_UD", "MATERIAL_3", "NOMER_DROBI_DIAMETR_KARTECHI", "TIP_TOVARA_1", "MATERIAL_RUKOYATI_NOZHI_UD", "NA", "NAZNACHENIE_1", "UROVEN", "VID", "OBSHCHAYA_DLINA_NOZHI_UD", "SVET", "TIP_OSNOVANIYA", "KREPLENIE_1", "TIP_4", "TIP_ZASIDKI", "TIP_NOZHA_NOZHI_UD", "PRIMANIVAEMAYA_DICH", "PRIMANIVAEMOE_ZHIVOTNOE_PTITSA_", "RASTSVETKA", "TIP_STALI_NOZHI_UD", "BREND", "KOMPLEKTNOST_TOVARA", "MATERIAL_4", "OBEM_ML_1", "OTSTROYKA_PARALLAKSA", "TIP_MISHENI_", "TOLSHCHINA_OBUKHA_NOZHI_UD", "DIAMETR_OBEKTIVA_RAZMER_LINZY_MM_2", "TIP_KRONSHTEYNA", "TIP_RASPYLENIYA", "TSVET_1", "KRATNOST_KH_3", "KREPLENIE", "TIP_TOVARA_NABORY_DLYA_CHISTKI", "DLINA_LEZVIYA", "KALIBR", "DLINA_NOZHA", "KALIBR_1", "RAZMER_1", "VES_PULKI", "MATERIAL_RUKOYATI", "KOLICHESTVO_V_BANKE", "MARKA_STALI", "DIAMETR_OBEKTIVA_RAZMER_LINZY_MM_3", "ISTOCHNIK_ENERGII_", "KOMPLEKTY_DLYA_SAYTA", "ELEMENT_PITANIYA", "DIAMETR_TRUBY_PRITSELA_MM", "NALICHIE_UPORA_", "RAZMER_AKSESSUAROV_", "TSVET_5", "DIAMETR_SHARIKA", "RAZMER_NOSKI", "ROST", "FOKALNAYA_PLOSKOST", "RAZMER_OBUV", "TIP", "TSENA_SHCHELCHKA_1", "KRATNOST_KH_4", "KREPLENIE_", "RAZMER", "RAZMER_ODEZHDA_ZHENSKAYA", "MATERIAL_1", "MATERIAL_5", "OBYEM_RYUKZAKI_", "DULNAYA_ENERGIYA", "TIP_KAMUFLYAZHA", "NACHALNAYA_SKOROST_PULI", "TSVET_2", "BLOUBEK", "OSNOVNOY_MATERIAL", "TIP_1", "PRIMANIVAEMOE_ZHIVOTNOE", "TSVET_3", "TIP_2", "TIP_KREPLENIYA_1", "MATERIAL_8", "SKLADNOE_IZGOLOVE", "TIP_OPORY", "VYSOTA_STULA", "MODEL_PISTOLETA_", "CHUVSTVITELNOST_SNR", "UPRAVLENIE_", "TSVET_LINZ", "DALNOST_OBNARUZHENIYA_CHELOVEKA_M", "TIP_TOVARA", "KRATNOST_KH_5", "NAZNACHENIE", "OBEM_ML", "RAZRESHENIE_MATRITSY", "DIAMETR_OBEKTIVA_RAZMER_LINZY_MM_4", "DLYA_ORUZHIYA_TYUNING", "MATERIAL_2", "EMKOST_TYUNING", "MATERIAL_6", "TSVET_4", "KALIBR_TYUNING", "KATEGORIYA_TYUNINGA_", "TIP_3", "MAKSIMALNYY_SVETOVOY_POTOK_LYUMEN", "MASSA_TYUNING", "MODEL_ORUZHIYA", "DIAMETR_OBEKTIVA_RAZMER_LINZY_MM_5", "OSNOVNOY_MATERIAL_TYUNING", "TIP_KREPLENIYA", "MATERIAL_7", "PATRON", "TSVET_LAZERA", "KALIBR_2", "PLATFORMA_TYUNING", "ISTOCHNIK_SVETA", "TIP_LTSU", "GRAVIROVANNAYA_SETKA", "PRINTSIP_DEYSTVIYA", "REZBA_TYUNING", "TIP_TYUNING", "HIT", "NEW_PRODUCT", "DOUBLE_BONUS", "BUY_WITH_THIS", ""),
		"PROPERTY_CODE_MOBILE" => array("DDPRO_IDPODRAZDELENIYAKONTRAGENTA", "DDPRO_DOKUMENTUCHETAPAKETA", "DDPRO_ISPOLZOVATTIPOVUYUPODSISTEMU1S", "DDPRO_RAZRESHITPODPISANIEBEZOTPRAVKI", "WEBSSYLKA_SPRAVOCHNIK_NOMENKLATURA_OBSHCHIE_", "DLINA_SM", "KOLICHESTVO", "KONTURPLAGIN_ID", "MATERIAL_LOZHA_PRIKLADA", "TIP_PATRONA", "DDPRO_DDPRO_IDPODRAZDELENIYAKONTRAGENTA", "DDPRO_ISPOLZOVATPODKLYUCHAEMYYMODUL", "DDPRO_ISPOLZOVATSOPOSTAVLENIEPODRAZDELENIY", "DDPRO_PODKLYUCHAEMYYMODULIMYASPRAVOCHNIKA", "VID_PTITSY", "KOLICHESTVO_STVOLOV", "KONTURPLAGIN_VERSIYA", "PRITSELNAYA_SETKA", "TIP_KAPSYULYA", "TIP_TERMOSA", "DDPRO_MESTONAKHOZHDENIEPODKLYUCHAEMOGOMODULYA", "DDPRO_OSNOVNOYPAKET", "DIAMETR_MM", "DLINA_STVOLA_STVOLOV", "KONTURPLAGIN_PROEKT", "OBYEM_L", "PODSVETKA_PRITSELNOY_SETKI", "PRIMECHANIE", "DDPRO_PODKLYUCHAEMYYMODULSSYLKA", "DDPRO_FORMAT_ID_UPD_SCHF", "VALYUTA", "VID_PRIZM", "VSTROENNNYY_BALLISTICHESKIY_KALKULYATOR", "KALIBR_3", "KONTURPLAGIN_SOSTOYANIE", "CML2_ARTICLE", "BREND_1", "DIAMETR_OBEKTIVA_RAZMER_LINZY_MM", "KALIBR_4", "PODSVETKA", "SIZE_DISCOUNT", "TIP_FONARYA", "GRUPPA_KALIBROV_", "KALIBR_5", "KRATNOST_KH", "TIP_OKULYARA", "MATERIAL_LOZHA_PRIKLADA_1", "OSNOVNOE_SVOYSTVO", "STEKLO_PRIZM", "TIP_KREPLENIYA_SOSHEK", "TSENA_SHCHELCHKA", "DIAMETR_KOLETS", "DLINA_STVOLA_MM", "KRATNOST_KH_1", "TIP_KOLLIMATORNOGO_PRITSELA", "VSTROENNYY_LAZERNYY_DALNOMER_", "DIAMETR", "EMKOST_MAGAZINA", "KRATNOST_", "MAKSIMALNOE_IZMERYAEMOE_RASSTOYANIE_M", "MINIMALNOE_IZMERYAEMOE_RASSTOYANIE_M", "PRINTSIP_DEYSTVIYA_1", "TSVET", "VES_PULI_G", "DIAMETR_OBEKTIVA_RAZMER_LINZY_MM_1", "DLINA", "DLINA_KLINKA_NOZHI_UD", "KRATNOST_KH_2", "MATERIAL", "TIP_PULI", "DIAMETR_1", "MARKA_STALI_NOZHI_UD", "MATERIAL_3", "NOMER_DROBI_DIAMETR_KARTECHI", "TIP_TOVARA_1", "MATERIAL_RUKOYATI_NOZHI_UD", "NA", "NAZNACHENIE_1", "UROVEN", "VID", "OBSHCHAYA_DLINA_NOZHI_UD", "SVET", "TIP_OSNOVANIYA", "KREPLENIE_1", "TIP_4", "TIP_ZASIDKI", "TIP_NOZHA_NOZHI_UD", "PRIMANIVAEMAYA_DICH", "PRIMANIVAEMOE_ZHIVOTNOE_PTITSA_", "RASTSVETKA", "TIP_STALI_NOZHI_UD", "BREND", "KOMPLEKTNOST_TOVARA", "MATERIAL_4", "OBEM_ML_1", "OTSTROYKA_PARALLAKSA", "TIP_MISHENI_", "TOLSHCHINA_OBUKHA_NOZHI_UD", "DIAMETR_OBEKTIVA_RAZMER_LINZY_MM_2", "TIP_KRONSHTEYNA", "TIP_RASPYLENIYA", "TSVET_1", "KRATNOST_KH_3", "KREPLENIE", "TIP_TOVARA_NABORY_DLYA_CHISTKI", "DLINA_LEZVIYA", "KALIBR", "DLINA_NOZHA", "KALIBR_1", "RAZMER_1", "VES_PULKI", "MATERIAL_RUKOYATI", "KOLICHESTVO_V_BANKE", "MARKA_STALI", "DIAMETR_OBEKTIVA_RAZMER_LINZY_MM_3", "ISTOCHNIK_ENERGII_", "KOMPLEKTY_DLYA_SAYTA", "ELEMENT_PITANIYA", "DIAMETR_TRUBY_PRITSELA_MM", "NALICHIE_UPORA_", "RAZMER_AKSESSUAROV_", "TSVET_5", "DIAMETR_SHARIKA", "RAZMER_NOSKI", "ROST", "FOKALNAYA_PLOSKOST", "RAZMER_OBUV", "TIP", "TSENA_SHCHELCHKA_1", "KRATNOST_KH_4", "KREPLENIE_", "RAZMER", "RAZMER_ODEZHDA_ZHENSKAYA", "MATERIAL_1", "MATERIAL_5", "OBYEM_RYUKZAKI_", "DULNAYA_ENERGIYA", "TIP_KAMUFLYAZHA", "NACHALNAYA_SKOROST_PULI", "TSVET_2", "BLOUBEK", "OSNOVNOY_MATERIAL", "TIP_1", "PRIMANIVAEMOE_ZHIVOTNOE", "TSVET_3", "TIP_2", "TIP_KREPLENIYA_1", "MATERIAL_8", "SKLADNOE_IZGOLOVE", "TIP_OPORY", "VYSOTA_STULA", "MODEL_PISTOLETA_", "CHUVSTVITELNOST_SNR", "UPRAVLENIE_", "TSVET_LINZ", "DALNOST_OBNARUZHENIYA_CHELOVEKA_M", "TIP_TOVARA", "KRATNOST_KH_5", "NAZNACHENIE", "OBEM_ML", "RAZRESHENIE_MATRITSY", "DIAMETR_OBEKTIVA_RAZMER_LINZY_MM_4", "DLYA_ORUZHIYA_TYUNING", "MATERIAL_2", "EMKOST_TYUNING", "MATERIAL_6", "TSVET_4", "KALIBR_TYUNING", "KATEGORIYA_TYUNINGA_", "TIP_3", "MAKSIMALNYY_SVETOVOY_POTOK_LYUMEN", "MASSA_TYUNING", "MODEL_ORUZHIYA", "DIAMETR_OBEKTIVA_RAZMER_LINZY_MM_5", "OSNOVNOY_MATERIAL_TYUNING", "TIP_KREPLENIYA", "MATERIAL_7", "PATRON", "TSVET_LAZERA", "KALIBR_2", "PLATFORMA_TYUNING", "ISTOCHNIK_SVETA", "TIP_LTSU", "GRAVIROVANNAYA_SETKA", "PRINTSIP_DEYSTVIYA", "REZBA_TYUNING", "TIP_TYUNING", "HIT", "NEW_PRODUCT", "DOUBLE_BONUS", "BUY_WITH_THIS"),
		"RCM_PROD_ID" => $_REQUEST["PRODUCT_ID"],
		"RCM_TYPE" => "personal",
		"SECTION_CODE" => "",
		"SECTION_ID" => "",
		"SECTION_ID_VARIABLE" => "SECTION_ID",
		"SECTION_URL" => "",
		"SECTION_USER_FIELDS" => array("", ""),
		"SEF_MODE" => "N",
		"SET_BROWSER_TITLE" => "N",
		"SET_LAST_MODIFIED" => "N",
		"SET_META_DESCRIPTION" => "N",
		"SET_META_KEYWORDS" => "N",
		"SET_STATUS_404" => "N",
		"SET_TITLE" => "N",
		"SHOW_404" => "N",
		"SHOW_ALL_WO_SECTION" => "N",
		"SHOW_CLOSE_POPUP" => "N",
		"SHOW_DISCOUNT_PERCENT" => "N",
		"SHOW_FROM_SECTION" => "N",
		"SHOW_MAX_QUANTITY" => "N",
		"SHOW_OLD_PRICE" => "N",
		"SHOW_PRICE_COUNT" => "1",
		"SHOW_SLIDER" => "Y",
		"SLIDER_INTERVAL" => "3000",
		"SLIDER_PROGRESS" => "N",
		"TEMPLATE_THEME" => "blue",
		"USE_ENHANCED_ECOMMERCE" => "N",
		"USE_MAIN_ELEMENT_SECTION" => "N",
		"USE_PRICE_COUNT" => "N",
		"USE_PRODUCT_QUANTITY" => "N",
        "OTHER_DATA" => [
            "OTHER_DATA_PROMO" => $arResult['DATA_SECTION_PROMO']['MB_PROMO'],
            "OTHER_DATA_SECTION_CATALOG" => $arResult['DATA_SECTION_PROMO']['MB_SECTION_CATALOG'],
			"OTHER_DATA_SLIDER" => $arResult['DATA_SLIDER']
		],
	)
);

$this->IncludeComponentTemplate();
