<?php

require($_SERVER["DOCUMENT_ROOT"] . "/bitrix/header.php");

$APPLICATION->IncludeComponent("bitrix:catalog.section.list", "section_list", [
    "ADD_SECTIONS_CHAIN" => "N",
    "CACHE_FILTER" => "N",
    "CACHE_GROUPS" => "N",
    "CACHE_TIME" => "36000000",
    "CACHE_TYPE" => "A",
    "COUNT_ELEMENTS" => "Y",
    "COUNT_ELEMENTS_FILTER" => "CNT_ACTIVE",
    "FILTER_NAME" => "sectionsFilter",
    "IBLOCK_ID" => "16",
    "IBLOCK_TYPE" => "1c_catalog",
    "SECTION_CODE" => "",
    "SECTION_FIELDS" => [
        0 => "ID",
        1 => "CODE",
        2 => "XML_ID",
        3 => "NAME",
        4 => "SORT",
        5 => "DESCRIPTION",
        6 => "PICTURE",
        7 => "DETAIL_PICTURE",
        8 => "IBLOCK_TYPE_ID",
        9 => "IBLOCK_ID",
        10 => "IBLOCK_CODE",
        11 => "IBLOCK_EXTERNAL_ID",
        12 => "",
    ],
    "SECTION_ID" => $_REQUEST["SECTION_ID"],
    "SECTION_URL" => "",
    "SECTION_USER_FIELDS" => [
        0 => "",
        1 => "",
    ],
    "SHOW_PARENT_NAME" => "N",
    "TOP_DEPTH" => isset($_REQUEST["DEPTH"]) ? $_REQUEST["DEPTH"] : 1,
		"VIEW_MODE" => "LIST",
	],
	false
);

$APPLICATION->IncludeComponent("bitrix:news.list", "about_benefits", [
    "ACTIVE_DATE_FORMAT" => "d.m.Y",
    "ADD_SECTIONS_CHAIN" => "N",
    "AJAX_MODE" => "N",
    "AJAX_OPTION_ADDITIONAL" => "",
    "AJAX_OPTION_HISTORY" => "N",
    "AJAX_OPTION_JUMP" => "N",
    "AJAX_OPTION_STYLE" => "N",
    "CACHE_FILTER" => "N",
    "CACHE_GROUPS" => "N",
    "CACHE_TIME" => "36000000",
    "CACHE_TYPE" => "A",
    "CHECK_DATES" => "Y",
    "DETAIL_URL" => "",
    "DISPLAY_BOTTOM_PAGER" => "N",
    "DISPLAY_DATE" => "N",
    "DISPLAY_NAME" => "N",
    "DISPLAY_PICTURE" => "N",
    "DISPLAY_PREVIEW_TEXT" => "N",
    "DISPLAY_TOP_PAGER" => "N",
    "FIELD_CODE" => [
        0 => "ID",
        1 => "CODE",
        2 => "NAME",
        3 => "PREVIEW_TEXT",
        4 => "PREVIEW_PICTURE",
        5 => "DETAIL_TEXT",
        6 => "DETAIL_PICTURE",
        7 => "IBLOCK_TYPE_ID",
        8 => "IBLOCK_ID",
        9 => "IBLOCK_CODE",
        10 => "IBLOCK_NAME",
        11 => "",
    ],
    "FILTER_NAME" => "",
    "HIDE_LINK_WHEN_NO_DETAIL" => "N",
    "IBLOCK_ID" => "15",
    "IBLOCK_TYPE" => "about",
    "INCLUDE_IBLOCK_INTO_CHAIN" => "N",
    "INCLUDE_SUBSECTIONS" => "N",
    "MESSAGE_404" => "",
    "NEWS_COUNT" => "20",
    "PAGER_BASE_LINK_ENABLE" => "N",
    "PAGER_DESC_NUMBERING" => "N",
    "PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
    "PAGER_SHOW_ALL" => "N",
    "PAGER_SHOW_ALWAYS" => "N",
    "PAGER_TEMPLATE" => ".default",
    "PAGER_TITLE" => "Новости",
    "PARENT_SECTION" => "238",
    "PARENT_SECTION_CODE" => "",
    "PREVIEW_TRUNCATE_LEN" => "",
    "PROPERTY_CODE" => [
        0 => "",
        1 => "",
    ],
    "SET_BROWSER_TITLE" => "N",
    "SET_LAST_MODIFIED" => "N",
    "SET_META_DESCRIPTION" => "N",
    "SET_META_KEYWORDS" => "N",
    "SET_STATUS_404" => "N",
    "SET_TITLE" => "N",
    "SHOW_404" => "N",
    "SORT_BY1" => "SORT",
    "SORT_BY2" => "",
    "SORT_ORDER1" => "ASC",
    "SORT_ORDER2" => "",
    "STRICT_SECTION_CHECK" => "N",
],
    false
);

require($_SERVER["DOCUMENT_ROOT"] . "/bitrix/footer.php");


